config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord

  enum status: { なし: 0, 未着手: 1, 着手: 2, 完了: 3 }
  enum priority: { 低: 0, 中: 1, 高: 2 }

  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { minimum: 1, maximum: 200 }
  validates :deadline, presence: true
  validates :status, presence: true
  validates :priority, presence: true

  belongs_to :user

  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings

  scope :search_name_status, ->(name, status) do
    where('name LIKE ?', "%#{name}%").where(status: status)
  end

  scope :search_name, ->(name) do
    where('name LIKE ?', "%#{name}%")
  end

  scope :search_status, ->(status) do
    where(status: status)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  before_update :not_update_admin_flg
  before_destroy :not_destroy_admin_flg

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, 
                    uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :tasks, dependent: :destroy

  private
  def not_update_admin_flg
    user = User.where(id: self.id).where(admin_flg: true)
    if User.where(admin_flg: true).count == 1 && user.present? && self.admin_flg == false
     throw(:abort)
    end
  end

  def not_destroy_admin_flg
    if self.admin_flg && User.where(admin_flg: true).count == 1
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all.includes(:tasks)
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id)
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @user.update(user_params)
      flash[:success] = 'ユーザを編集しました。'
      redirect_to admin_user_path(@user.id)
    else
      flash.now[:danger] = 'ユーザの編集に失敗しました。'
      render :edit
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def destroy
    if @user.destroy
      flash[:success] = 'ユーザを削除しました。'
      redirect_to admin_users_path
    else
      flash[:danger] = 'ユーザの削除に失敗しました。'
      redirect_to admin_users_path
    end
  end
  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin_flg)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :current_user

  before_action :authenticate_user, if: proc { !((controller_path == 'users' && action_name == 'new') ||
                                                (controller_path == 'sessions' && action_name == 'new') ||
                                                (controller_path == 'users' && action_name == 'create') ||
                                                (controller_path == 'sessions' && action_name == 'create')) }
  before_action :not_authenticate_user, if: proc { controller_path == 'users' && action_name == 'new' }
  before_action :admin_user, if: proc { controller_path == 'admin/users' }

  def authenticate_user
    if @current_user == nil
      flash[:danger] = 'ログインしてください'
      redirect_to new_session_path
    end
  end

  def not_authenticate_user
    if @current_user != nil
      flash[:danger] = 'ログアウトしてください'
      redirect_to user_path(@current_user.id)
    end
  end

  def admin_user
    if @current_user != nil
      if @current_user.admin_flg == false
        flash[:danger] = '管理者以外はアクセスできません'
        redirect_to tasks_path
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'ログインしました'
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:success] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  PER = 3

  def index
    if params[:label_id]
      @tasks = @current_user.tasks.joins(:labels).where(labels: { id: params[:label_id] }).page(params[:page]).per(PER)
    elsif params[:sort_expired]
      @tasks = @current_user.tasks.order("deadline DESC").page(params[:page]).per(PER)
    elsif params[:sort_priority]
      @tasks = @current_user.tasks.order("priority DESC").page(params[:page]).per(PER)
    elsif params[:name] && params[:status] && !(params[:status] == 'なし') && !(params[:name] == '')
      @tasks = @current_user.tasks.search_name_status(params[:name], params[:status]).page(params[:page]).per(PER)
    elsif params[:name] && (params[:status] == 'なし') && !(params[:name] == '')
      @tasks = @current_user.tasks.search_name(params[:name]).page(params[:page]).per(PER)
    elsif params[:status] && (params[:status] != 'なし') && (params[:name] == '')
      @tasks = @current_user.tasks.search_status(params[:status]).page(params[:page]).per(PER)
    else
      @tasks = @current_user.tasks.order("created_at DESC").page(params[:page]).per(PER)
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:success] = 'タスクを登録しました。'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクの登録に失敗しました。'
      render new_task_path
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'タスクを編集しました。'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクの編集に失敗しました。'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = 'タスクを削除しました。'
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(
      :name,
      :content,
      :deadline,
      :status,
      :priority,
      :user_id, 
      { label_ids: [] }
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'ログインしました'
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
    redirect_to tasks_path if @current_user.id != @user.id
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/admin/users/edit.html.erb
<h1>編集</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :admin_flg %>
  <%= f.check_box :admin_flg %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/admin/users/index.html.erb
<h1>ユーザ一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>ユーザ名</th>
      <th>タスク数</th>
      <th>管理者権限</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.tasks.count %></td>
        <% if user.admin_flg %>
          <td>あり</td>
        <% else %>
          <td>なし</td>
        <% end %>
        <td><%= link_to '詳細', admin_user_path(user) %></td>
        <td><%= link_to '編集', edit_admin_user_path(user) %></td>
        <td><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ユーザを登録する', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>新規登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :admin_flg %>
  <%= f.check_box :admin_flg %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<% if @user.admin_flg %>
  <p>管理者権限: あり</p>
<% else %>
  <p>管理者権限: なし</p>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>登録日時</th>
      <th>ステータス</th>
      <th>優先順位</th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline.strftime('%Y-%m-%d') %></td>
        <td><%= task.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/flash_messages' %>
      <% if logged_in? %>
        <%= link_to "タスク一覧", tasks_path %>
        <%= link_to "マイページ", user_path(current_user.id) %>
        <% if current_user.admin_flg %>
          <%= link_to "管理画面", admin_users_path %>
        <% end %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "新規登録", new_user_path %>
        <%= link_to "ログイン", new_session_path %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <% if msg.instance_of?(Array) %>
    <% msg.each do |m| %>
      <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= m %>
      </div>
    <% end %>
  <% else %>
    <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div>
      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :deadline %>
    <%= form.date_field :deadline, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :label %>
    <br>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>

  <%= form.hidden_field :user_id, value: @current_user.id %>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render 'form', task: @task %>

<%= link_to '詳細', @task %> |
<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<%= form_with url: tasks_path, method: :get, local: true do |f| %>
  <%= f.label :タスク名 %>
  <%= f.text_field :name, id: 'task_name_field' %>
  <%= f.label :ステータス %>
  <%= f.select :status, Task.statuses.keys, {}, id: 'status_field' %>
  <%= f.submit :検索%>
<% end %>

<%= form_with url: tasks_path, method: :get, local: true do |f| %>
  <%= f.label :ラベル名 %>
  <%= f.select("label_id", Label.pluck(:name, :id)) %>
  <%= f.submit :ラベルで検索 %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>登録日時</th>
      <th>ステータス</th>
      <th>優先順位</th>
      <th>ラベル</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline.strftime('%Y-%m-%d') %></td>
        <td><%= task.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td>
          <% task.labels.each do |label| %>
            <%= label.name %>
          <% end %>
        </td>
        <td><%= link_to '詳細', task %></td>
        <td><%= link_to '編集', edit_task_path(task) %></td>
        <td><%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @tasks %>

<br>

<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %> |
<%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %> |
<%= link_to 'タスクを登録する', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク登録</h1>

<%= render 'form', task: @task %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>

<p>
  <strong>タスク名:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>タスク詳細:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>終了期限:</strong>
  <%= @task.deadline.strftime('%Y-%m-%d') %>
</p>

<p>
  <strong>登録日時:</strong>
  <%= @task.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
</p>

<p>
  <strong>ステータス:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>優先順位:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>ラベル:</strong>
  <% @task.labels.each do |label| %>
    <%= label.name %>
  <% end %>
</p>

<%= link_to '編集', edit_task_path(@task) %> |
<%= link_to '戻る', tasks_path %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>